config/routes.rb
# rubocop:disable Metrics/BlockLength
Rails.application.routes.draw do

  root 'homepages#index'

  devise_for :users, skip: [:sessions]
  as :user do
    get 'login', to: 'devise/sessions#new', as: :new_user_session
    post 'login', to: 'devise/sessions#create', as: :user_session
    get 'logout', to: 'devise/sessions#destroy', as: :destroy_user_session
  end

  resources :admin, only: %i[index]
  namespace :admin do

    resources :resources do
      member do
        get 'preview'
      end
      collection do
        post :upload, to: 'uploads#create'
      end
    end

    resources :groupings do
      member do
        get 'preview'
      end
    end

    resources :events do
      member do
        get 'preview'
      end
    end

    resource :user, only: [:edit] do
      collection do
        patch 'update_password'
      end
    end

    resource :api do
      member do
        get 'resource', to: 'api#resource'
      end
    end

    resources :people
    resources :teams
    resources :livestreams

    post :graphics, to: 'graphics#create'
    post :locations, to: 'locations#create'
  end

  resource :api, only: [:index] do
    member do
      get 'one21', to: 'api#one21'
      get 'resource', to: 'api#resource'
    end
  end

  get :blog, to: 'resources#blog'
  get 'preaching/:id', to: 'resources#series'
  get :preaching, to: 'resources#index'
  get :live, to: 'livestreams#index'

  resources :podcasts, path: :podcast do
    collection do
      get 'sermon'
    end
  end

  # Migrate oontent out…
  get 'export/blog', to: 'export#blog'
  get 'export/audio', to: 'export#audio'
  get 'export/series', to: 'export#series'

  resources :resources, only: %i[show]
  get :resources, to: redirect('/preaching')

  resources :events, only: %i[index show] do
    member do
      # instances _might_ not have slugs, and that's okay.
      get '/:date', constraints: { date: /\d{4}-\d{2}-\d{2}/}, to: 'events#instance'
      get '/:instance_id', to: 'events#instance'
    end
  end

  resources :people, only: %i[show]

  get "/*id" => 'pages#show', as: :page, format: false
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Globe Admin</title>
    <%= stylesheet_link_tag 'admin', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>

  <body>

    <header class="m-admin-header">
      <a href="#" class="m-admin-header--menu js-admin-nav-toggle">
        <%= svg_tag('admin-menu', class: 'js-admin-nav-icon')%>
      </a>

      <div class="m-admin-header--logo">
        <%= link_to svg_tag('tgc-logo-long-no-ring-themed'), "/" %>
      </div>

      <div class="m-admin-header--user">
        <%= image_tag(gravatar_url(current_user.email, {size: 55, d: 'mm'}),
                      srcset: "#{gravatar_url(current_user.email, {size: 110, d: 'mm'})} 2x",
                      alt: 'My account') %>

        <ul class="m-admin-header--user--subnav">
          <li><%= link_to "Sign out", destroy_user_session_path %></li>
          <li><%= link_to "Change your password", edit_admin_user_path %></li>
        </ul>
      </div>
    </header>

    <nav class="m-admin-nav js-admin-nav">
      <%= link_to(admin_resources_path, class: 'm-admin-nav--link') do %>
        <%= svg_tag('admin-menu', class: 'm-admin-nav--link--icon')%>
        <span class='m-admin-nav--link--text'>Resources</span>
      <% end %>

      <%= link_to(admin_groupings_path, class: 'm-admin-nav--link') do %>
        <%= svg_tag('admin-menu', class: 'm-admin-nav--link--icon')%>
        <span class='m-admin-nav--link--text'>Groups and Series</span>
      <% end %>

      <%= link_to(admin_people_path, class: 'm-admin-nav--link') do %>
        <%= svg_tag('admin-menu', class: 'm-admin-nav--link--icon')%>
        <span class='m-admin-nav--link--text'>People</span>
      <% end %>

      <%= link_to(admin_teams_path, class: 'm-admin-nav--link') do %>
        <%= svg_tag('admin-menu', class: 'm-admin-nav--link--icon')%>
        <span class='m-admin-nav--link--text'>Teams</span>
      <% end %>

      <%= link_to(admin_events_path, class: 'm-admin-nav--link') do %>
        <%= svg_tag('admin-menu', class: 'm-admin-nav--link--icon')%>
        <span class='m-admin-nav--link--text'>Events</span>
      <% end %>

      <%= link_to(admin_livestreams_path, class: 'm-admin-nav--link') do %>
        <%= svg_tag('admin-menu', class: 'm-admin-nav--link--icon')%>
        <span class='m-admin-nav--link--text'>Livestreams</span>
      <% end %>
    </nav>

    <%= yield %>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <script>
      window.__assets = {
        externalSirTrevorIcons: '<%= asset_path('sir-trevor-icons.svg') %>'
      };
    </script>

    <% if Rails.env.development? %>
    <%= javascript_include_tag 'vendors' %>
    <% end %>
    <%= javascript_include_tag 'bundle' %>
  </body>
</html>